name: CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build_release:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        arch:
          - x64
        include:
          - os: ubuntu-24.04-arm
            arch: arm64
    name: ${{ matrix.os }}, target=${{ matrix.arch }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: npm install

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.arch }}" = "x86" ]; then
            echo "ARCH=ia32" >> $GITHUB_ENV
          else
            echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: npm run prebuild -a ${{ env.ARCH }}

      - name: Run tests
        run: npm test

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v5
        with:
          name: prebuilt-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds
          retention-days: 1

      - name: Upload binaries to GitHub Release
        run: npm run upload ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/')
  publish:
    needs: build_release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: prebuilds
          merge-multiple: true
      - name: Publish
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
